---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-chubao
---
apiVersion: chubao.rook.io/v1alpha1
kind: ChubaoCluster
metadata:
  name: mycluster
  namespace: rook-chubao
spec:
  image: chubaofs/cfs-server:0.0.1
  imagePullPolicy: IfNotPresent
  dataDirHostPath: /var/lib/chubao
  logDirHostPath: /var/log/chubao
  #  priorityClassName: chubaofs-high-priority
  #  cleanupPolicy: None
  master:
    replicas: 3
    logLevel: "error"
    retainLogs: 2001
    port: 17111
    prof: 17121
    exporterPort: 17131
    metanodeReservedMem: 77108864
  metaNode:
    zone: ""
    logLevel: "error"
    totalMem: 26843545600
    port: 17211
    prof: 17221
    exporterPort: 17231
    raftHeartbeatPort: 17241
    raftReplicaPort: 17251
  dataNode:
    zone: "zone"
    logLevel: "error"
    port: 17311
    prof: 17321
    exporterPort: 17331
    raftHeartbeatPort: 17341
    raftReplicaPort: 17351
    disks:
      - /data0:21474836480
      - /data1:21474836480
  consul:
    port: 8501
    image: consul:1.6.1
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
  provisioner:
    driverName: "csi.chubaofs.com"
    kubeletPath: /var/lib/kubelet
    csiChubaoFS:
      image: chubaofs/cfs-csi-driver:2.2.1.110.0
      resources:
        limits:
          cpu: "500m"
          memory: "1024Mi"
      #        requests:
      #          cpu: "500m"
      #          memory: "1024Mi"
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "rook-chubao/csi"
                    operator: In
                    values:
                      - chubaofs
    csiProvisioner:
    #      image: quay.io/k8scsi/csi-provisioner:v1.6.0
    #      resources:
    #        limits:
    #          cpu: "500m"
    #          memory: "1024Mi"
    #        requests:
    #          cpu: "500m"
    #          memory: "1024Mi"
    csiAttacher:
    #      image: quay.io/k8scsi/csi-attacher:v2.0.0
    #      resources:
    #        limits:
    #          cpu: "500m"
    #          memory: "1024Mi"
    #        requests:
    #          cpu: "500m"
    #          memory: "1024Mi"
    csiRegister:
#      image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
#      resources:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
