apiVersion: chubao.rook.io/v1alpha1
kind: ChubaoCluster
metadata:
  name: mycluster
  namespace: rook-chubao
spec:
  cfsVersion:
    serverImage: chubaofs/cfs-server:2.0.5
    imagePullPolicy: IfNotPresent

  # The path on the host where configuration files will be persisted. Must be specified.
  # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
  # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
  dataDirHostPath: /var/lib/rook
  logDirHostPath: /var/log/rook

  master:
    replicas: 3
    logLevel: error
    retainLogs: 2000
    port: 17010
    prof: 17020
    exporterPort: 9500
    metanodeReservedMem: 67108864
#    resources:
#      requests:
#        memory: "8Gi"
#        cpu: "2000m"
#      limits:
#        memory: "32Gi"
#        cpu: "8000m"
  metaNode:
    logLevel: error
    totalMem: 26843545600
    port: 17210
    prof: 17220
    raftHeartbeat: 17230
    raftReplica: 17240
    exporterPort: 9510
#    resources:
#      requests:
#        memory: "32Gi"
#        cpu: "2000m"
#      limits:
#        memory: "256Gi"
#        cpu: "8000m"
  dataNode:
    logLevel: error
    port: 17310
    prof: 17320
    raftHeartbeat: 17330
    raftReplica: 17340
    exporterPort: 9520
    disks:
      - /data0:21474836480
      - /data1:21474836480
#    resources:
#      requests:
#        memory: "8Gi"
#        cpu: "2000m"
#      limits:
#        memory: "32Gi"
#        cpu: "8000m"
  consul:
    port: 8500
    image: consul:1.6.1
    imagePullPolicy: IfNotPresent
#    resources:
#      requests:
#        memory: "256Mi"
#        cpu: "100m"
#      limits:
#        memory: "512Mi"
#        cpu: "500m"
