---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-chubao
---
apiVersion: chubao.rook.io/v1alpha1
kind: ChubaoCluster
metadata:
  name: mycluster
  namespace: rook-chubao
spec:
  cfsVersion:
    serverImage: chubaofs/cfs-server:0.0.1
  dataDirHostPath: /var/lib/rook
  logDirHostPath: /var/log/rook
  master:
    metanodeReservedMem: 67108864
  metaNode:
    totalMem: 524288000 
  dataNode:
    disks:
      - /data0:52428800
---
apiVersion: chubao.rook.io/v1alpha1
kind: ChubaoMonitor
metadata:
  name: mymonitor
  namespace: rook-chubao
spec:
  prometheus:
    image: prom/prometheus:v2.13.1
    imagePullPolicy: IfNotPresent
    port: 9090
    hostPath: 
      Path: /var/lib/chubaofs_prometheus
    consulUrl: http://consul-service.rook-chubao.svc.cluster.local:8500
  grafana:
    image: grafana/grafana:6.4.4
    imagePullPolicy: IfNotPresent
    port: 3000
