---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-chubao
---
apiVersion: chubao.rook.io/v1alpha1
kind: ChubaoCluster
metadata:
  name: mycluster
  namespace: rook-chubao
spec:
  image: chubaofs/cfs-server:0.0.1
  imagePullPolicy: IfNotPresent
  dataDirHostPath: /var/lib/chubao
  logDirHostPath: /var/log/chubao
#  priorityClassName: chubaofs-high-priority
#  cleanupPolicy: None
  master:
    replicas: 3
    logLevel: "error"
    retainLogs: 2000
    port: 17110
    prof: 17120
    exporterPort: 17130
    metanodeReservedMem: 67108864
  metaNode:
    zone: ""
    logLevel: "error"
    totalMem: 26843545600
    port: 17210
    prof: 17220
    exporterPort: 17230
    raftHeartbeatPort: 17240
    raftReplicaPort: 17250
  dataNode:
    zone: ""
    logLevel: "error"
    port: 17310
    prof: 17320
    exporterPort: 17330
    raftHeartbeatPort: 17340
    raftReplicaPort: 17350
    disks:
      - /data0:21474836480
      - /data1:21474836480
  consul:
    port: 8500
    image: consul:1.6.1
  #    resource:
  #      limits:
  #        cpu: "500m"
  #        memory: "1024Mi"
  #      requests:
  #        cpu: "500m"
  #        memory: "1024Mi"
  provisioner:
    driverName: "csi.chubaofs.com"
    kubeletPath: /var/lib/kubelet
    csiChubaoFS:
    #      image: chubaofs/cfs-csi-driver:2.2.1.110.0
    #      resource:
    #        limits:
    #          cpu: "500m"
    #          memory: "1024Mi"
    #        requests:
    #          cpu: "500m"
    #          memory: "1024Mi"
    csiProvisioner:
    #      image: quay.io/k8scsi/csi-provisioner:v1.6.0
    #      resource:
    #        limits:
    #          cpu: "500m"
    #          memory: "1024Mi"
    #        requests:
    #          cpu: "500m"
    #          memory: "1024Mi"
    csiAttacher:
    #      image: quay.io/k8scsi/csi-attacher:v2.0.0
    #      resource:
    #        limits:
    #          cpu: "500m"
    #          memory: "1024Mi"
    #        requests:
    #          cpu: "500m"
    #          memory: "1024Mi"
    csiRegister:
#      image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
#      resource:
#        limits:
#          cpu: "500m"
#          memory: "1024Mi"
#        requests:
#          cpu: "500m"
#          memory: "1024Mi"
