---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-chubao
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chubaoclusters.chubao.rook.io
spec:
  group: chubao.rook.io
  names:
    kind: ChubaoCluster
    listKind: ChubaoClusterList
    plural: chubaoclusters
    singular: chubaocluster
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chubaomonitors.chubao.rook.io
spec:
  group: chubao.rook.io
  names:
    kind: ChubaoMonitor
    listKind: ChubaoMonitorList
    plural: chubaomonitors
    singular: chubaomonitor
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chubaoobjectstores.chubao.rook.io
spec:
  group: chubao.rook.io
  names:
    kind: ChubaoObjectStore
    listKind: ChubaoObjectStoreList
    plural: chubaoobjectstores
    singular: chubaoobjectstore
  scope: Namespaced
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rook-chubao-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - memcached-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups:
      - chubao.rook.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-chubao-operator
  namespace: rook-chubao
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-chubao-operator
subjects:
  - kind: ServiceAccount
    name: rook-chubao-operator
roleRef:
  kind: Role
  name: rook-chubao-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-chubao-operator
---