---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-chubao-operator
  namespace: rook-chubao
spec:
  serviceAccount: rook-chubao-operator
  selector:
    matchLabels:
      app: rook-chubao-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: rook-chubao-operator
    spec:
      containers:
        - name: rook-chubao-operator
          image: chubaofs/cfs-operator:0.0.1
          args: ["chubao", "operator"]
