---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-cfs-pvc-demo
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cfs-sc